### 1. Create a 3x3x3 array with random values


In [2]:
import numpy as np

In [31]:

a=np.arange(9).reshape(3,3)
print("   3 X 3 RANDOM INTEGER NUMBER:")
print(a)
from numpy import random
x = random.rand(3,3)
print("   3 X 3 RANDOM FLOAT NUMBER")
print(x)


   3 X 3 RANDOM INTEGER NUMBER:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
   3 X 3 RANDOM FLOAT NUMBER
[[0.63712109 0.59568161 0.62504368]
 [0.02464995 0.82539126 0.8412992 ]
 [0.52917371 0.50753326 0.99015679]]


##  5x5 matrix with values 1,2,3,4 just below the diagonal

In [33]:
element=[1,2,3,4,5]
value=np.diag(v)
value

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# Create a 8x8 matrix and fill it with a checkerboard pattern

In [77]:
value=np.zeros((8,8))
value[1:2,::2]=1
value[::2,1:2]=1
value

array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

 # Normalize a 5x5 random matrix
 

In [83]:
print("ARRANGE VALUES")
b=np.arange(25).reshape(5,5)
print(b)
print("RANDOM VALUES")
c=np.random.random((5,5))
print(c)

ARRANGE VALUES
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
RANDOM VALUES
[[0.37156688 0.65463281 0.83886203 0.53955524 0.98388272]
 [0.28682709 0.13848357 0.30757622 0.20904891 0.97288535]
 [0.27995349 0.15743635 0.21160363 0.39157963 0.94582323]
 [0.13306312 0.64102184 0.92512151 0.00158267 0.83199933]
 [0.80028245 0.44457381 0.00413604 0.33878735 0.74458357]]


# How to find common values between two arrays

In [92]:
a1 = np.array([0, 10, 20, 40, 60])
print("A1: ",array1)
a2 = [10, 30, 40]
print("A2: ",array2)
print("Intersected values:")
print(np.intersect1d(a1, a2))

A1:  [ 0 10 20 40 60]
A2:  [10, 30, 40]
Intersected values:
[10 40]


# The dates of yesterday, today and tomorrow

In [93]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-08-02
Today:  2020-08-03
Tomorrow:  2020-08-04


# Consider two random array A and B, check if they are equal

In [97]:
a1 = np.array([0, 10, 20, 40, 60])
print("A1: ",array1)
a2 = [10, 30, 40]
print("A2: ",array2)
print("Is both arrays are equal values:")
check = np.array_equal(a1,a2)
print(check)

A1:  [ 0 10 20 40 60]
A2:  [10, 30, 40]
Is both arrays are equal values:
False


# random vector of size 10 and replace the maximum value by 0

In [101]:
vector=np.random.random(10)
vector
vector[vector.argmax()]=0
vector

array([0.        , 0.04133273, 0.03788939, 0.17515739, 0.83697335,
       0.19533082, 0.59334393, 0.60856126, 0.31638645, 0.26018131])

# print all the values of an array

In [102]:
vector=np.random.random(10)
vector

array([0.2590683 , 0.78678419, 0.26825253, 0.04495243, 0.89051635,
       0.10788461, 0.72083733, 0.051563  , 0.32793892, 0.88059001])

# Subtract the mean of each row of a matrix

In [22]:
arr=np.array([[5,2],[6,9]])
print("the array is:")
print(arr)
row_mean=np.mean(arr,axis=1)
print("row_mean value is:")
print(row_mean)
print("subtracted mean of each row matrix is:")
print(arr-row_mean)


the array is:
[[5 2]
 [6 9]]
row_mean value is:
[3.5 7.5]
subtracted mean of each row matrix is:
[[ 1.5 -5.5]
 [ 2.5  1.5]]


# add 1 to each element indexed by a second vector

In [25]:
arr=np.array([5,2,7,8,9])
print("the array is:",arr)
print("after adding one:",arr+1)

the array is: [5 2 7 8 9]
after adding one: [ 6  3  8  9 10]


# get the diagonal of a dot product

In [33]:
a1 = np.array([[1,2],[3,4]])
b1= np.array([[3,5],[6,5]])
print(a1)
print(b1)
print("the dot product value is :")
print(np.dot(A,B))
out=np.diag(np.dot(A, B))
print("diagonal of a dot product is....",out)

[[1 2]
 [3 4]]
[[3 5]
 [6 5]]
the dot product value is :
[[15 15]
 [33 35]]
diagonal of a dot product is.... [15 35]


# most frequent value in an array

In [35]:
x = np.random.randint(0, 10, 20)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[5 5 6 7 2 5 5 9 7 4 1 4 1 9 7 5 7 2 9 7]
Most frequent value in the above array:
5


 # get the n largest values of an array

In [43]:
a=[5,6,7,89,43,56,78,32]
sor=np.array(a)
print (sort[np.argsort(sort)[-1:]])

[89]


 # create a record array from a regular array

In [47]:
one=np.array([1,2,3,4])
two=np.array(['Red','Green','White','Orange'])
three=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([one, two, three],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
